### ISSUE TITLE
Null Pointer @ DataManager

### ISSUE THREAD

**Issue by rascafr** [rascafr/ESEOmegaV2-Current#3]
After Lydia payment

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
    at fr.bde_eseo.eseomega.lacommande.DataManager.fillData(DataManager.java:109)
    at fr.bde_eseo.eseomega.lacommande.tabs.TabListFood$AsyncGetData.onPostExecute(TabListFood.java:178)
    at fr.bde_eseo.eseomega.lacommande.tabs.TabListFood$AsyncGetData.onPostExecute(TabListFood.java:157)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rascafr** [comment]
Resolved @ 3.1.1
